apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-war
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-war
  template:
    metadata:
      labels:
        app: java-war
    spec:
      containers:
      - name: java-war
        image: java-war:2.0 # Replace with your image name
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: java-war-service
spec:
  selector:
    app: java-war
  ports:
  - name: http
    port: 9003
    targetPort: 8080
  type: LoadBalancer